# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sklepgorski

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_92b8a321964a4e2cae750847893473ab }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2895fff8fcf3403fa72fe1cbfbbb9205 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_92b8a321964a4e2cae750847893473ab }}/wentyl23/e_biznes_1.0:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sklepgorski'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9e403b5bedcf4978adece59f853e8d8a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_92b8a321964a4e2cae750847893473ab }}/wentyl23/e_biznes_1.0:${{ github.sha }}'